version: "3.8"
name: "electric-81-db"

configs:
  postgres_config:
    file: "./postgres.conf"

volumes:
  pg_data:

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: tc01
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    command:
      - -c
      - wal_level=logical
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  electric:
    image: electricsql/electric:0.8.1
    init: true
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/tc01
      PG_PROXY_PORT: 65432
      PG_PROXY_PASSWORD: "postgres"
      LOGICAL_PUBLISHER_HOST: electric
      AUTH_MODE: insecure
      # Enabling debug will provide TONS of logs, some useful.
      # LOG_LEVEL: debug
    ports:
      - "5133:5133"
      - "65432:65432"
    depends_on:
      - postgres
